version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
        - echo "pre_build now"
        #- mkdir build cfn
        #- cp *.html build/
        #- cp cfn-* cfn/
    #   - echo "Installing dependencies and packaging jar file - `pwd`"
    #   - cd orders-service && mvn package
    #   - echo "Jar file package `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
    #   - aws cloudformation package --template-file app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
    #   - aws cloudformation package --template-file test-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file test-output_sam.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - source/*
    - cloudformation/cfn-service.yml
    # - test-output_sam.yaml
  #discard-paths: yes
