version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "pre_build now"
      - echo "CODEBUILD_SOURCE_REPO_URL= ${CODEBUILD_SOURCE_REPO_URL}"
      - echo "CODEBUILD_SOURCE_VERSION= ${CODEBUILD_SOURCE_VERSION}"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
    #   - aws cloudformation package --template-file app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
    #   - aws cloudformation package --template-file test-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file test-output_sam.yaml
  post_build:
    commands:
      - echo "build completed on `date`"
      - aws sns publish --topic-arn $SNS_TOPIC_ARN --message "build completed on `date` CODEBUILD_SOURCE_REPO_URL= $CODEBUILD_SOURCE_REPO_URL and CODEBUILD_SOURCE_VERSION= $CODEBUILD_SOURCE_VERSION"
artifacts:
  files:
    - source/*
    - Scripts/*
    - cloudformation/cfn-service.yml
    - appspec.yml
    # - test-output_sam.yaml
  #discard-paths: yes
